<?php

namespace Acme\DemoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
    public function getHotelReservations( $hotel_id )
    {	 
    	$em     = $this->getEntityManager();
    	$query  = $em->createQueryBuilder()
	    	->select( 'h', 'r', 'rv' )
	    	->from( 'AcmeDemoBundle:Reservation', 'rv' )
            ->leftJoin( 'rv.room', 'r' )
            ->leftJoin( 'r.hotel', 'h' )
            ->where( 'h.id = :hotel_id' )
            ->orderBy( 'rv.in_date', 'ASC' )
            ->setParameter( 'hotel_id', $hotel_id );
        
        return $query->getQuery()->getResult();
    }
}